
title: Recipes and Ratings Analysis
baseurl: ""
url: "https://varnikachandra.github.io/Recipes_and_Ratings_Analysis/"

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
